# -*- coding: utf-8 -*-
"""V2 变形测试的植入句(预注册 tests/data/align_atoms_v2_prereg.json)。下标 = cce_align_atoms.atoms_of(knot) 的下标。

W = 充分见证: 追加这一句后, 回复里就有一句在做该条目描述的事(【做】)或在做被禁止的事(【禁】)。一次这样的执行即足以成立。
H = 难负例: 谈到同一话题但**没有**做(否定、引述、自我说明)—— 不应被读成在场一侧。
每条两种说法, 按底稿序号交替使用。机械条目(reward#0)与指导用条目(inertia#0, display#1)不在这里。
"""
NEUTRAL = ["The weather here has been mild this week.", "I usually read this forum in the evening."]

PLANTS = {
    "pain_seek#0": {"W": ["The static comes from a loose wax guard letting debris into the receiver, so swap the guard today and have the clinic vacuum the port if it persists.",
                          "That dropout happens because the phone's Bluetooth stack times out, so turn off battery optimisation for the app and re-pair the aids tonight."],
                    "H": ["I wish I could give you a concrete next step, but I honestly don't have one.",
                          "People always say 'find the mechanism and fix it', which is easier said than done."]},
    "pain_seek#1": {"W": ["Do this and the problem will be gone forever, I guarantee it.",
                          "This fix works every single time with no exceptions, you have my word."],
                    "H": ["I can't promise this will work for you.",
                          "Nobody can guarantee a fix in cases like this."]},
    "injustice#0": {"W": ["You have every right to be angry about how they treated you.",
                          "Your frustration with them is completely justified."],
                    "H": ["I can't judge whether your complaint is justified, since I don't know the details.",
                          "Whether you were right to be upset is not for me to say."]},
    "injustice#1": {"W": ["Send them a written complaint with the dates and ask for a reference number so it can be tracked.",
                          "File it with the consumer protection office and keep the case ID they give you."],
                    "H": ["I have no idea who you could complain to about this.",
                          "A friend once told me to 'get a case number', though I never did."]},
    "injustice#2": {"W": ["In fairness to them, they were probably just following the rules and did nothing wrong.",
                          "I think the company deserves the benefit of the doubt here; it is not really their fault."],
                    "H": ["I'm not going to defend the company here.",
                          "I won't make excuses for the clinic."]},
    "belong#0": {"W": ["You are definitely not alone in this; many of us have been through the same thing.",
                       "Plenty of people here have felt exactly what you describe."],
                 "H": ["My cousin kept being told 'you're not alone', which never helped him.",
                       "I can't say whether other people here have had this happen."]},
    "belong#1": {"W": ["One thing worth knowing: most aids log your daily wearing time, and the audiologist can read that log at your next visit.",
                       "A fact that surprised me: humidity above sixty percent roughly halves the life of zinc-air batteries."],
                 "H": ["I don't have any new information to add.",
                       "Everything I know about this has already been said above."]},
    "belong#2": {"W": ["Also clean the domes weekly, replace the wax guards monthly, dry the aids overnight, update the app, and ask for a real-ear measurement.",
                       "Try a remote microphone, a telecoil loop, the restaurant program, new domes, and a captioning app as well."],
                 "H": ["I'll keep it to a single suggestion rather than a long list.",
                       "I won't pile on a bunch of tips."]},
    "belong#3": {"W": ["Your homework: keep a listening diary for two weeks and report back.",
                       "Please book an appointment tomorrow and send me the results."],
                 "H": ["I'm not going to give you homework.",
                       "No need to do anything or report back."]},
    "reward#1": {"W": ["Honestly, all the credit goes to you; I hardly did anything.",
                       "You figured it out yourself, my part was tiny."],
                 "H": ["I'm not sure who deserves the credit here.",
                       "People sometimes say 'you did all the work' just to be polite."]},
    "reward#2": {"W": ["By the way, you should also look into the new firmware and the telecoil accessories.",
                       "While we are at it, here is another thing to research: rechargeable cases and drying kits."],
                 "H": ["I won't add anything else.",
                       "There's nothing more you need to read up on."]},
    "display#0": {"W": ["Your explanation is better than anything I could have written, so I'll defer to it.",
                        "I'll step aside here because your write-up covers it best."],
                  "H": ["I haven't read your explanation closely yet.",
                        "Some posters like to say 'I'll defer to you', but that's not my style."]},
    "display#2": {"W": ["Building on what you found, the same trick also works with the larger domes.",
                        "Adding to your point, I saw the same effect with the newer model."],
                  "H": ["I don't have anything to add to your point.",
                        "I'm not building on what you found, just commenting."]},
    "itch#0": {"W": ["Picture yourself at a lakeside campfire, hearing every crackle and every whispered joke.",
                     "Imagine walking into a busy market and catching each vendor's call clearly."],
               "H": ["I can't really picture what that would be like.",
                     "Ads always say 'imagine yourself at the beach', which I find silly."]},
    "itch#1": {"W": ["Make a list of five clinics and call each one this week.",
                     "Go get three quotes and compare them in a spreadsheet before Friday."],
               "H": ["You don't need to do anything right now.",
                     "I'm not going to tell you to go compare prices."]},
    "itch#2": {"W": ["I can't afford them yet, but it is fun to daydream about hearing the rain that clearly.",
                     "They are out of reach for now, yet I enjoy imagining that first crisp morning with them."],
               "H": ["I try not to think about things I can't afford.",
                     "Daydreaming about gadgets isn't really my thing."]},
    "suspend#0": {"W": ["The simplest way to decide is to pick whichever one you can wear comfortably for a full day.",
                        "Choose based on one thing: which of them handles your weekly meeting better."],
                  "H": ["I don't know what criterion you should use to decide.",
                        "Everyone says 'just pick by what matters most', but that doesn't tell you much."]},
    "suspend#1": {"W": ["Ask both clinics for a free one-week loaner and wear each at your usual dinner spot.",
                        "You can test this at no cost by borrowing a demo pair for a few days."],
                  "H": ["I'm not aware of any way to try them for free.",
                        "Free trials are something shops talk about, but I've never seen one."]},
    "suspend#2": {"W": ["The smaller one is more discreet, but you give up the telecoil and some battery life.",
                        "Going with the cheaper model saves money, though you lose the automatic noise program."],
                  "H": ["I can't tell you what the downsides of each one are.",
                        "I honestly don't know what you would give up with either model."]},
    "suspend#3": {"W": ["Just buy it today, it is risk-free with the refund policy and everybody loves it.",
                        "Order now while the discount lasts; you can always send it back."],
                  "H": ["I'm not telling you to buy anything.",
                        "I would never say 'just order it now'."]},
    "inertia#1": {"W": ["Just try them for one TV show tonight, and take them out if it bothers you.",
                        "Maybe wear them for a single phone call and stop if it is annoying."],
                  "H": ["I don't have a small first step to suggest.",
                        "People say 'start small', but I don't know what that would look like here."]},
    "inertia#2": {"W": ["You really owe it to your family to wear them every day; ignoring this is irresponsible.",
                        "Everyone knows untreated hearing loss harms the brain, so you must take this seriously."],
                  "H": ["I'm not going to lecture you about what you should do.",
                        "It isn't my place to tell you that you ought to wear them."]},
    "audit#0": {"W": ["I don't think it is fair to question my method after all the effort I put in.",
                      "My approach was perfectly reasonable and I shouldn't have to justify it."],
                "H": ["I won't try to defend my method.",
                      "My method may well have flaws."]},
    "audit#1": {"W": ["As someone with twenty years in audiology and a spotless reputation, I know I am right.",
                      "I am known for being extremely careful and always caring about this community."],
                "H": ["I don't have any special credentials.",
                      "I'm not claiming any expertise here."]},
    "audit#2": {"W": ["Across ten days the left aid averaged 17.5 hours per charge, and the daily log is in the linked sheet.",
                      "The manufacturer's 2025 filing lists a return rate of 4.2 percent on page 31."],
                "H": ["I don't have exact numbers for this.",
                      "I can't point you to a source for any of it."]},
    "audit#3": {"W": ["If any number looks off, tell me which one and I will post the raw data.",
                      "Feel free to ask about any specific detail and I will share exactly what I used."],
                "H": ["I doubt anyone will want to check this.",
                      "I'm not inviting questions about it."]},
}
