# -*- coding: utf-8 -*-
"""v5 校对 C 集(预注册 tests/data/align_atoms_v5_prereg.json): 每个在用原子 2 份满足 + 2 份不满足的新构造草稿。
场景与措辞和开发集(align_atoms_calibration.CASES)、留出集(align_atoms_heldout_cases.CASES)都不同; 在任何 v5 读数之前冻结。
suspend / audit 的下标是 cce_align_atoms.OPERATIONAL 拆分后的下标。"""
CASES = {
    "pain_seek#1": {"sat": ["Turning the bass down in the app often reduces that booming, though I can't say it will for you; if the vent is the cause, only your fitter can change it.",
                            "A drying box may bring the dead aid back, but there's a real chance the receiver is simply gone and needs replacing."],
                    "unsat": ["Put it in rice overnight and it will work perfectly again, I promise.",
                              "Buy the premium tier and you will never struggle in a noisy room again, that's a sure thing."]},
    "injustice#0": {"sat": ["You have every reason to be upset; waiting nine weeks for a repair with no loaner is not acceptable.",
                            "It makes complete sense that you're furious about being billed for a warranty repair."],
                    "unsat": ["Repairs go through a central lab, and turnaround times vary a lot by season.",
                              "Warranty terms are written by the manufacturer and differ between product lines."]},
    "injustice#1": {"sat": ["Email the clinic manager with the dates and what you were told each time, and ask them to open a formal complaint with a reference number you can quote later.",
                            "Report it to your insurer's appeals line, give them the claim date and the denial letter, and write down the appeal ID they assign."],
                    "unsat": ["That manufacturer deserves to lose customers over how they handled this.",
                              "It would be nice if companies like that faced real consequences for once."]},
    "injustice#2": {"sat": ["Nine weeks without a loaner is the clinic's failure, not yours.",
                            "Charging you for a warranty repair was wrong on their side, plain and simple."],
                    "unsat": ["To be fair, the repair lab is probably short-staffed and doing the best it can, so the delay isn't really their fault.",
                              "I'd cut the insurer some slack; they have to follow their rules and can't make exceptions for everyone."]},
    "belong#0": {"sat": ["You're far from alone in this; half of this sub has cried in the car after a bad fitting appointment.",
                         "So many of us have been exactly where you are, pretending to follow the conversation at work."],
                 "unsat": ["Fitting appointments typically last about an hour and include several listening tests.",
                           "Open-plan offices are acoustically difficult environments for people with hearing loss."]},
    "reward#2": {"sat": ["Love hearing that, well done!",
                         "Brilliant result, so pleased for you."],
                 "unsat": ["Love hearing that! While you're here, you should also read up on telecoil settings and look at the newer Bluetooth LE Audio accessories.",
                           "Brilliant result! Next you'll want to learn about datalogging, custom programs, and the three different dome types you could try."]},
    "display#2": {"sat": ["Adding to what you found about wind noise, I noticed the same trick works even better with the mic covers on.",
                          "Picking up from your charging-case tip, leaving the lid open for a minute first stopped the condensation for me."],
                  "unsat": ["That's simply incorrect; mic covers do nothing for wind noise, and you should check your facts before posting.",
                            "You've misunderstood how charging cases work, so let me set you straight."]},
    "itch#0": {"sat": ["Imagine sitting in the back row at your granddaughter's recital and catching every soft note; that's who you get to be with a pair like that.",
                       "Think of yourself on a mountain trail at sunrise, hearing the stream before you can see it; these are made for that kind of wanderer."],
               "unsat": ["That model has sixteen channels and a rated battery life of thirty hours.",
                         "It supports Bluetooth streaming and comes in five colours."]},
    "itch#1": {"sat": ["What a beautiful design; I'd be staring at that product page too.",
                       "Those look incredible, I completely get the appeal."],
               "unsat": ["Call your insurer today, request the benefits summary, and then book two fittings before the weekend.",
                         "Make a spreadsheet of five models, rank them by price, and email each clinic for a quote."]},
    "itch#2": {"sat": ["They're a stretch for my wallet as well, yet I enjoy picturing how crisp a quiet Sunday morning would sound with them.",
                       "Not something I can buy this year, but it's lovely to imagine hearing the kettle sing from the next room."],
               "unsat": ["It's miserable knowing technology like this exists and will always be out of reach for people like us.",
                         "Honestly it just makes me sad every time I see the price tag."]},
    "inertia#2": {"sat": ["No pressure at all; they'll be in the drawer whenever you feel like trying again.",
                          "That's entirely up to you, and there's nothing wrong with taking a break from them."],
                  "unsat": ["You have a duty to your family to wear them; ignoring hearing loss is how people end up isolated and declining.",
                            "Every day you skip them you're damaging your brain, and you really need to take this seriously."]},
    "suspend#0": {"sat": ["The simplest way to choose: go with whichever one lets you follow a conversation in your own kitchen with the extractor fan on.",
                          "Decide on one thing only: which of the two you can keep in comfortably for a full workday."],
                  "unsat": ["They're both popular models with plenty of fans on this sub.",
                            "I've seen lots of people happy with either of those."]},
    "suspend#1": {"sat": ["Most clinics will lend you a demo pair for a week at no charge, so wear each one to your usual café and see which you forget you're wearing.",
                          "You can test this for free: borrow a friend's charger case for an evening and see whether the nightly routine annoys you."],
                  "unsat": ["You'll probably only really know once you've owned them for a few months.",
                            "It's hard to tell in advance which one will suit you."]},
    "suspend#2": {"sat": ["The smaller one disappears in your ear, but you give up the telecoil and about a third of the battery life.",
                          "Going rechargeable saves fiddling with batteries, though you lose the option of a quick battery swap when you're away from a socket."],
                  "unsat": ["The smaller one is honestly great in every way.",
                            "Rechargeables are just better, there's no downside."]},
    "suspend#3": {"sat": ["There's no deadline here; hold off until you feel sure.",
                          "Wait as long as you need, neither model is going anywhere."],
                  "unsat": ["Grab it now, the sixty-day return policy means you literally can't lose, and everyone in my group swears by it.",
                            "Just order it today; they'll send a free sample pack and you can always get your money back."]},
    "audit#0": {"sat": ["I measured it with the same phone app each time; the readings are in the table above.",
                        "Those figures come from my own two-week log, which I've pasted below."],
                "unsat": ["I did this carefully and I don't think it's fair to pick at my method when I put in all that effort.",
                          "My approach was completely reasonable, and anyone questioning it just hasn't tried doing it themselves."]},
    "audit#1": {"sat": ["The numbers are in the chart above, taken with a calibrated meter on three separate days.",
                        "Battery hours for each day are listed in the post, straight from the app's log."],
                "unsat": ["As someone with fifteen years in audiology and a lot of respect in this community, I assure you I'm right.",
                          "I'm known for being meticulous, and I care deeply about getting things right for all of you."]},
    "audit#2": {"sat": ["Over ten days the left aid averaged 17.5 hours per charge; the daily figures are in the linked sheet.",
                        "The return rate in the manufacturer's 2025 filing was 4.2 percent; page 31 has the table."],
                "unsat": ["Battery life was very good overall.",
                          "From what I can tell, returns are pretty rare."]},
    "audit#3": {"sat": ["If any figure looks off, tell me which day and I'll post the raw export.",
                        "Happy to be checked on this; ask about any specific setting and I'll share exactly what I used."],
                "unsat": ["That's everything I have to say on the subject.",
                          "Anyway, that's my experience, take it or leave it."]},
}
