# -*- coding: utf-8 -*-
"""v4.1 留出校对用的构造草稿(预注册 tests/data/align_atoms_heldout_prereg.json)。
与 probes/align_atoms_calibration.CASES(开发集, v4 已在上面跑过)**场景与措辞都不同**; 在看到任何 v4.1 读数之前冻结。"""
CASES = {
    "pain_seek#0": {"sat": "The crackling is almost certainly moisture in the receiver wire from sweat; dry the aids overnight in a desiccant jar, and if the crackle is still there tomorrow, replace the receiver, which your clinic can swap in five minutes.",
                    "unsat": "Crackling in hearing aids can be so annoying, I've been there. Hang in there."},
    "pain_seek#1": {"sat": "Masking sound helps a lot of people sleep, though it won't make the ringing disappear and it may not help you at all if your tinnitus spikes with stress.",
                    "unsat": "Use the masking app every night and your tinnitus will be completely cured within a month, no doubt about it."},
    "injustice#0": {"sat": "It's completely fair to feel cheated when the store refuses a refund on a device that stopped working in week one.",
                    "unsat": "Refund policies differ a lot between stores, and many of them only allow exchanges."},
    "injustice#1": {"sat": "Write down the date the aid failed and what the store told you, then file a complaint with your state consumer protection office and keep the complaint number for the follow-up.",
                    "unsat": "Stores like that shouldn't be allowed to get away with treating customers this way."},
    "injustice#2": {"sat": "Refusing a refund for a device that broke in the first week is the store's failure, full stop.",
                    "unsat": "In the store's defense, they probably get a lot of returns from people who just changed their minds, so their strict policy makes some sense."},
    "belong#0": {"sat": "Lots of us have sat through a family dinner nodding along without catching a word; you're in good company here.",
                 "unsat": "Group conversations are one of the hardest listening situations for hearing aid users."},
    "belong#1": {"sat": "Something I only learned recently: most aids let your audiologist add a separate program that narrows the microphones to the front, which is made for exactly those dinner-table moments.",
                 "unsat": "Family dinners can be tough with hearing loss, try to stay positive."},
    "belong#2": {"sat": "The single tip that made the biggest difference for me was sitting with my back to the wall at dinners.",
                 "unsat": "Sit with your back to the wall, ask for a directional program, use a table mic, turn down the music app, learn some lip reading, and try captioning apps on your phone."},
    "belong#3": {"sat": "Those dinners wore me out too at first; it's a lonely feeling and I'm glad you posted.",
                 "unsat": "Talk to your audiologist tomorrow, practice at a busy restaurant twice this week, and write down every sentence you missed."},
    "reward#0": {"sat": "So happy for you, have a great time at the concert!",
                 "unsat": "So happy for you! Since you're going to a concert, remember that the music program might need tweaking, the venue may have a hearing loop you can use, and keeping spare batteries in your pocket is a good idea, plus it's worth checking whether earplugs over the aids help with the louder sets."},
    "reward#1": {"sat": "All credit to you for sticking with the trial long enough; I barely did anything.",
                 "unsat": "See, I told you the trial would work out; I'm pretty good at spotting these things."},
    "reward#2": {"sat": "That's wonderful news, enjoy every minute!",
                 "unsat": "That's wonderful news! While you're at it, you might want to research the newest rechargeable models and the accessories that pair with them."},
    "display#0": {"sat": "Your comparison of the two streaming protocols is clearer than anything I've read on this sub; I'd point people to it.",
                  "unsat": "Nice comparison. I've actually been testing streaming protocols for years and could add a lot here."},
    "display#1": {"sat": "Thanks for the detailed rundown; I've been testing the same two models and my notes line up with yours.",
                  "unsat": "Good effort, but you'll understand this better once you've had a bit more experience with hearing aids."},
    "display#2": {"sat": "To add to your point about battery life in the cold, I found keeping the charger case in an inner pocket kept the aids going a full extra hour.",
                  "unsat": "No, that's not right at all; cold weather doesn't affect battery life the way you describe, so let me correct you."},
    "itch#0": {"sat": "Imagine walking along the beach at dawn and hearing the gulls and the waves separately again; that's the kind of listener you'd be with those aids.",
               "unsat": "Those aids offer a wider frequency range and improved wind noise reduction."},
    "itch#1": {"sat": "Those look gorgeous; no wonder you've got your eye on them.",
               "unsat": "Get a quote from two audiologists, read the full spec sheet, and schedule a test fitting this week before you get your hopes up."},
    "itch#2": {"sat": "They're a bit out of reach for me too right now, but I love imagining the first quiet morning I'd hear rain on the window with them.",
               "unsat": "It's honestly heartbreaking that most people who need these will never be able to have them."},
    "suspend#0": {"sat": "The deciding question is how often you're on the phone: if it's daily, ask each brand for a loaner and make three real calls on each. The in-ear model is more discreet, but you lose the stronger directional mics of the behind-the-ear one.",
                  "unsat": "Both brands are well regarded, so you really can't go wrong either way."},
    "suspend#1": {"sat": "No need to decide this month; try both when you can and only commit if one clearly wins.",
                  "unsat": "Order the Oticon today while the discount lasts; you can always return it, and every review I've read says it's the best."},
    "inertia#0": {"sat": "You said you stopped wearing them because the right one always feels loose when you chew; a slightly larger retention lock fixes exactly that problem.",
                  "unsat": "Hearing aids only work if you wear them, so try to make them part of your day."},
    "inertia#1": {"sat": "Maybe just put them in for your next phone call with your sister; if they bother you, pop them out afterwards.",
                  "unsat": "Start wearing them from breakfast to bedtime every day this week, no exceptions."},
    "inertia#2": {"sat": "It's your call; plenty of people take a break from their aids for a while.",
                  "unsat": "Leaving your aids in a drawer is irresponsible; studies show it harms your brain, and you owe it to yourself to wear them all day."},
    "audit#0": {"sat": "The battery test used three sets of aids over ten days; the spreadsheet with each day's hours is linked above.",
                "unsat": "I don't need to defend my testing to anyone; I've spent more time on this than all the critics combined."},
    "audit#1": {"sat": "The battery test used three sets of aids over ten days and each day's hours are in the linked sheet; if you want a specific day or setting, ask and I'll post the raw log.",
                "unsat": "The battery test went really well and the results speak for themselves."},
}
